<?php
/**
 * Service
 *
 * PHP version 5
 *
 * @category Class
 * @package  KuntaAPI
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kunta API
 *
 * One API to rule them all. One API to find them, One API to bring them all and in the darkness bind them.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace KuntaAPI\Model;

use \ArrayAccess;

/**
 * Service Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     KuntaAPI
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Service implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Service';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'id' => 'string',
        'descriptions' => '\KuntaAPI\Model\ServiceDescription[]',
        'name' => '\KuntaAPI\Model\LocalizedValue[]',
        'sourceIds' => 'string[]',
        'classIds' => 'string[]',
        'electronicChannelIds' => 'string[]',
        'phoneChannelIds' => 'string[]',
        'printableFormChannelIds' => 'string[]',
        'serviceLocationChannelIds' => 'string[]',
        'webpageChannelIds' => 'string[]'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'id' => 'id',
        'descriptions' => 'descriptions',
        'name' => 'name',
        'sourceIds' => 'source_ids',
        'classIds' => 'class_ids',
        'electronicChannelIds' => 'electronic_channel_ids',
        'phoneChannelIds' => 'phone_channel_ids',
        'printableFormChannelIds' => 'printable_form_channel_ids',
        'serviceLocationChannelIds' => 'service_location_channel_ids',
        'webpageChannelIds' => 'webpage_channel_ids'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'id' => 'setId',
        'descriptions' => 'setDescriptions',
        'name' => 'setName',
        'sourceIds' => 'setSourceIds',
        'classIds' => 'setClassIds',
        'electronicChannelIds' => 'setElectronicChannelIds',
        'phoneChannelIds' => 'setPhoneChannelIds',
        'printableFormChannelIds' => 'setPrintableFormChannelIds',
        'serviceLocationChannelIds' => 'setServiceLocationChannelIds',
        'webpageChannelIds' => 'setWebpageChannelIds'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'id' => 'getId',
        'descriptions' => 'getDescriptions',
        'name' => 'getName',
        'sourceIds' => 'getSourceIds',
        'classIds' => 'getClassIds',
        'electronicChannelIds' => 'getElectronicChannelIds',
        'phoneChannelIds' => 'getPhoneChannelIds',
        'printableFormChannelIds' => 'getPrintableFormChannelIds',
        'serviceLocationChannelIds' => 'getServiceLocationChannelIds',
        'webpageChannelIds' => 'getWebpageChannelIds'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['descriptions'] = isset($data['descriptions']) ? $data['descriptions'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['sourceIds'] = isset($data['sourceIds']) ? $data['sourceIds'] : null;
        $this->container['classIds'] = isset($data['classIds']) ? $data['classIds'] : null;
        $this->container['electronicChannelIds'] = isset($data['electronicChannelIds']) ? $data['electronicChannelIds'] : null;
        $this->container['phoneChannelIds'] = isset($data['phoneChannelIds']) ? $data['phoneChannelIds'] : null;
        $this->container['printableFormChannelIds'] = isset($data['printableFormChannelIds']) ? $data['printableFormChannelIds'] : null;
        $this->container['serviceLocationChannelIds'] = isset($data['serviceLocationChannelIds']) ? $data['serviceLocationChannelIds'] : null;
        $this->container['webpageChannelIds'] = isset($data['webpageChannelIds']) ? $data['webpageChannelIds'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param string $id Unique identifier representing a specific service.
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets descriptions
     * @return \KuntaAPI\Model\ServiceDescription[]
     */
    public function getDescriptions()
    {
        return $this->container['descriptions'];
    }

    /**
     * Sets descriptions
     * @param \KuntaAPI\Model\ServiceDescription[] $descriptions
     * @return $this
     */
    public function setDescriptions($descriptions)
    {
        $this->container['descriptions'] = $descriptions;

        return $this;
    }

    /**
     * Gets name
     * @return \KuntaAPI\Model\LocalizedValue[]
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param \KuntaAPI\Model\LocalizedValue[] $name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets sourceIds
     * @return string[]
     */
    public function getSourceIds()
    {
        return $this->container['sourceIds'];
    }

    /**
     * Sets sourceIds
     * @param string[] $sourceIds Name of the service.
     * @return $this
     */
    public function setSourceIds($sourceIds)
    {
        $this->container['sourceIds'] = $sourceIds;

        return $this;
    }

    /**
     * Gets classIds
     * @return string[]
     */
    public function getClassIds()
    {
        return $this->container['classIds'];
    }

    /**
     * Sets classIds
     * @param string[] $classIds List of service classes
     * @return $this
     */
    public function setClassIds($classIds)
    {
        $this->container['classIds'] = $classIds;

        return $this;
    }

    /**
     * Gets electronicChannelIds
     * @return string[]
     */
    public function getElectronicChannelIds()
    {
        return $this->container['electronicChannelIds'];
    }

    /**
     * Sets electronicChannelIds
     * @param string[] $electronicChannelIds
     * @return $this
     */
    public function setElectronicChannelIds($electronicChannelIds)
    {
        $this->container['electronicChannelIds'] = $electronicChannelIds;

        return $this;
    }

    /**
     * Gets phoneChannelIds
     * @return string[]
     */
    public function getPhoneChannelIds()
    {
        return $this->container['phoneChannelIds'];
    }

    /**
     * Sets phoneChannelIds
     * @param string[] $phoneChannelIds
     * @return $this
     */
    public function setPhoneChannelIds($phoneChannelIds)
    {
        $this->container['phoneChannelIds'] = $phoneChannelIds;

        return $this;
    }

    /**
     * Gets printableFormChannelIds
     * @return string[]
     */
    public function getPrintableFormChannelIds()
    {
        return $this->container['printableFormChannelIds'];
    }

    /**
     * Sets printableFormChannelIds
     * @param string[] $printableFormChannelIds
     * @return $this
     */
    public function setPrintableFormChannelIds($printableFormChannelIds)
    {
        $this->container['printableFormChannelIds'] = $printableFormChannelIds;

        return $this;
    }

    /**
     * Gets serviceLocationChannelIds
     * @return string[]
     */
    public function getServiceLocationChannelIds()
    {
        return $this->container['serviceLocationChannelIds'];
    }

    /**
     * Sets serviceLocationChannelIds
     * @param string[] $serviceLocationChannelIds
     * @return $this
     */
    public function setServiceLocationChannelIds($serviceLocationChannelIds)
    {
        $this->container['serviceLocationChannelIds'] = $serviceLocationChannelIds;

        return $this;
    }

    /**
     * Gets webpageChannelIds
     * @return string[]
     */
    public function getWebpageChannelIds()
    {
        return $this->container['webpageChannelIds'];
    }

    /**
     * Sets webpageChannelIds
     * @param string[] $webpageChannelIds
     * @return $this
     */
    public function setWebpageChannelIds($webpageChannelIds)
    {
        $this->container['webpageChannelIds'] = $webpageChannelIds;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\KuntaAPI\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\KuntaAPI\ObjectSerializer::sanitizeForSerialization($this));
    }
}


